Auto tooltip position
oruga-ui/oruga pull request #372
Opened 2022-06-16 01:07 UTC by blm768

Fixes #105

Basic testbench is [here](https://github.com/blm768/oruga-tooltip-test).

## Proposed Changes

- Tooltips' `position` prop now accepts the value `"auto"`.
- Auto tooltip positioning picks the side that maximizes how much of the tooltip is visible onscreen.
- To break ties, auto positioning favors the default tooltip position.

## Open Questions

- This solution assumes an arrow size of zero rather pulling the value from CSS.
  - Is that good enough given that the arrow size is generally small?
- Should we add a small margin around the edge of the viewport so the tooltip doesn't run right up against it?

## To Do

- [ ] Test on mobile browsers; they handle viewports differently when zooming.
- [ ] Backport to Vue 2

2022-06-18 05:25 UTC, jtommy commented
I'll review soon in order to answer to all open questions.

2022-08-31 17:34 UTC, blm768 commented
Any thoughts on the open questions? I'm still interested in getting this merged if it'll add value.

2022-09-02 06:18 UTC, jtommy commented
You are completely right, after the new release I'll give a try

2022-09-26 19:35 UTC, jtommy commented
> This solution assumes an arrow size of zero rather pulling the value from CSS. Is that good enough given that the arrow size is generally small?

Yes, I think it's right... if anything we can add a prop to customize it (low priority)

>  Should we add a small margin around the edge of the viewport so the tooltip doesn't run right up against it?

Can you make an example?

> Should auto be the default value for the position prop?

Probably in the next breaking release

2022-09-26 20:42 UTC, blm768 commented
> > Should we add a small margin around the edge of the viewport so the tooltip doesn't run right up against it?
>
> Can you make an example?

Right now, we let the tooltip use its preferred position as long as it doesn't extend outside the viewport. In the first example in the image below, the tooltip is fully within the viewport, but it does run into the edge, so if it had a drop shadow, the shadow might be cut off by the viewport edge. If we consider that enough of a problem that we should do something about it, we could switch to an alternate position (shown here in gray) when the tooltip gets within, say, 5 pixels of the edge rather than at the point it actually crosses the edge.

![example](https://user-images.githubusercontent.com/2198455/192376006-9c0c1a5a-e533-4791-bcd6-0197d079eed3.svg)

> Are you able to support the Vue 2 version too?

Yep. I'm starting on that right now.

2022-09-27 20:20 UTC, blm768 commented
OK, I've put in the Vue 2 changes, and those seem to be working as expected. I also made a small change to how we compute the `isWebKit` flag so we can compensate for Edge's misbehavior.

2022-09-27 20:24 UTC, blm768 commented
I've also made the commit messages a little more descriptive.

2022-09-27 20:59 UTC, jtommy requested changes

2022-09-27 22:22 UTC, jtommy approved these changes

2022-09-27 22:22 UTC, blm768 commented on packages/oruga-next/src/components/tooltip/Tooltip.vue
> +                    console.debug("isWebKit: ", isWebKit);
Oh, oops. Yeah, that was never supposed to actually get committed. I've pushed a separate commit that removes that, but I can squash that in with a quick rebase before this gets merged.

2022-09-27 22:23 UTC, blm768 commented
OK, fixups are squashed in.

2022-09-27 22:24 UTC, merged

2022-09-27 22:24 UTC, jtommy commented
@blm768 thanks a lot! I'll add an example in the docs-next too

2022-09-27 22:30 UTC, jtommy commented
@blm768 do you think we might use the sane approach on dropdown? It might be really helpful to add that feature to it and components that use it (datepicker, etc)

2022-09-28 05:39 UTC, blm768 commented
> Do you think we might use the same approach on dropdown?

I haven't looked too closely at the source yet, but I imagine it'd be possible to generalize this to work pretty much the same way with dropdowns. Depending on how we want them to behave, we might use different rules for repositioning them, and we might need to make more effort to handle long dropdowns (e.g. scroll to bring them onscreen, test cases where they're simply too long to fit onscreen) than we would for long tooltips just because dropdowns tend to run longer overall. At the very least, the check for whether the element is offscreen should be basically the same for both kinds of controls.